### ISSUE TITLE
Platform style review

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/smartcitizen-web#340]
## 1. MAP VIEW

- [x] Change “search” bar colour to #4D4D4D and try to avoid the problem with the “X” icon background
- [x] Change “success” notifications bar (green) to #4DBD4E
- [x] Use the #6e6e6e colour for the “We can also take you to your nearest online kit by letting us know your location.” Text below “no kit selected”
- [x] Use the #ffc100 yellow for the “caution” notifications bar
- [x] Change the text colour in the drop-down menu from “Community” to #6e6e6e
- [x] Use the #2e2e2e colour for the “no kit selected” text on main screen
- [x] Take a look at the green dot that appears while searching “Barcelona”, what is it?
- [x] Use the main blue #0C2EFB for the “alternative kits” pop-up, which are currently on grey
- [x] Change the colour of the “filters, tags” texts to #2e2e2e, (same for its icons)
- [x] When filters are applied, make #FFF the background of the upper section that shows the results. i.e: “#Ground Floor 10 kits are on #Ground Floor and 30% are active today.”

## 2. SELECTED KIT

- [x] Update the colours of the charts following the new sketch file
- [x] Use the following colours for the kits tags: DARK #FFD44D / LIGHT #FFECB3 (Text should be the darkest grey #2e2e2e)
- [x] Change the colour of the active sensor value and its description text to #2e2e2e
- [x] Change kits names/titles to #2e2e2e
- [x] Change colour of the username (below the kit information) to #2e2e2e
- [x] Change colour of the icons on the “kit information” section to #6e6e6e
- [x] Use the main blue for the “get your kit and join us” button
- [x] Adjust colors in the in the “time period selection” modal = month name to #2e2e2e, left and right arrows to #6e6e6e, day of the week #6e6e6e, today corner icon #0C2EFB, clear red icon #FF3D4C, close “x” icon #6e6e6e, selected day background #FFC100, selected day text #2e2e2e
- [x] Change to the main yellow #FFC100 the dot beside the name of the kit (currently on light blue)

## 3. PLATFORM MODALS

- [x] Change titles colour (currently on blue) to #2e2e2e
- [x] Change the colour of top buttons/links (sign up, request) to the main blue #0C2EFB
- [x] On “get your kit” modal, change the colour of the check icons to #6e6e6e
- [x] Change the colour of the texts beside the top buttons (Already have an account?, New here?, Forgot your password?…) to #6e6e6e
- [x]  The modal of GET YOUR KIT (in the menu), it's too wide and tall. Also, sometimes it's impossible to scroll down and use the action button below.

### 4.1 Kits tab:

- [x] Set “not configured” status colour to #FF3D4C
- [x] Set “never published” status colour to #ffc100
- [x] Set “has published” status colour to #4DBD4E
- [x] Change the colour of the kits location and version to #6e6e6e
- [x] Change the colour of the icons #6e6e6e
- [x] Change colour of the texts at the drop-down menu to #6e6e6e (when clicking on edit icon)

### 4.2 User tab:

- [x] Change colour of the key "icons" to #6e6e6e

### 4.3 Tools tab:

- [x] Change the colour of the external links to #2e2e2e
- [x] Change the colour of the text below the links to #6e6e6e

## 5. GENERAL

- [x] Change the colour of the logo on loading animation to #6e6e6e
