### ISSUE TITLE
restyling webapp SCK 2.0

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/smartcitizen-web#346]
- [ ]  Add padding on the content: 20px (top) 30px (left) 30px (right)
- [ ] Change top bar color to #262626
- [ ] Change CYAN text color to #0C2EFB
- [ ] Change CYAN button color to #FFC100 and the text on it to #262626
- [ ] Change GREEN alert color to #8CC252
- [ ] Change RED alert color to #FF3D4C
- [ ] Change the logo for the full-white version: https://smartcitizen.me/assets/images/smartcitizen_logo.svg
