### ISSUE TITLE
Checklist for 2.0 launch

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-web#371]
When we separate this angular page from the [campaign](https://new.smartcitizen.me) / landing page we need to:
- [ ] Remove the current landing page
- [ ] Choose a new default landing page. 
   * Will the site be less slow, if we make the default only include ONLINE and INSIDE?
   * World map? 
   * Or a lighter page which does not load +1000 devices?
- [ ] After logging in, redirect the user to:
   * His profile page where he manages his kits?
   * Maybe the user would rather want to be directed to his profile? Instead of going to the world map.
- [ ] Check login/signup issue #370

**Comment by pral2a** [comment]
Good work!
